apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "hello-world-chart.selectorLabels" . | nindent 4 }}
